packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  default:
    builder: "make"
    base: "quay.io/madebymany/build-bases:bionic"
    build_depends:
      - yasm
      - pkg-config
    packages:
      - type: debian
        name: libav-tools
        version: 7:3.3.4-2
        target: install
        repos:
          - mxm-public
