packages:
  branch_codenames:
    master: focal-unstable
    production: focal-stable

jobs:
  default:
    builder: "make"
    base: "quay.io/madebymany/build-bases:focal"
    build_depends:
      - yasm
      - pkg-config
    packages:
      - type: debian
        name: libav-tools
        target: install
        repos:
          - mxm-public
